var searchData=
[
  ['a_0',['a',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2changelog.html#autotoc_md44',1,'2.0.1 - 2015/07/26 - &lt;a href=&quot;https://github.com/shirriff/Arduino-IRremote/releases/tag/BETA&quot; &gt;Release&lt;/a&gt;'],['../index.html#autotoc_md163',1,'&lt;a href=&quot;https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/changelog.md&quot; &gt;History&lt;/a&gt;'],['../index.html#autotoc_md165',1,'&lt;a href=&quot;https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/Contributors.md&quot; &gt;Contributors&lt;/a&gt;']]],
  ['a_20href_20https_3a_20github_20com_20arduino_20irremote_20arduino_20irremote_20blob_20master_20changelog_20md_20history_20a_1',['&lt;a href=&quot;https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/changelog.md&quot; &gt;History&lt;/a&gt;',['../index.html#autotoc_md163',1,'']]],
  ['a_20href_20https_3a_20github_20com_20arduino_20irremote_20arduino_20irremote_20blob_20master_20contributors_20md_20contributors_20a_2',['&lt;a href=&quot;https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/Contributors.md&quot; &gt;Contributors&lt;/a&gt;',['../index.html#autotoc_md165',1,'']]],
  ['a_20href_20https_3a_20github_20com_20shirriff_20arduino_20irremote_20releases_20tag_20beta_20release_20a_3',['2.0.1 - 2015/07/26 - &lt;a href=&quot;https://github.com/shirriff/Arduino-IRremote/releases/tag/BETA&quot; &gt;Release&lt;/a&gt;',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2changelog.html#autotoc_md44',1,'']]],
  ['a_20motor_4',['Receiving stops after analogWrite() or tone() or after running a motor.',['../index.html#autotoc_md117',1,'']]],
  ['a_20robot_20car_5',['IR control of a robot car',['../index.html#autotoc_md145',1,'']]],
  ['a_20star_6',['If you find this program useful, please give it a star.',['../index.html#autotoc_md60',1,'']]],
  ['access_20the_20strong_20raw_20data_20strong_20use_3a_7',['To access the &lt;strong&gt;RAW data&lt;/strong&gt;, use:',['../index.html#autotoc_md86',1,'']]],
  ['adding_20new_20protocols_8',['Adding new protocols',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md55',1,'']]],
  ['addition_20you_20address_20with_20your_20pr_9',['Cover &lt;strong&gt;all&lt;/strong&gt; occurences of the problem / addition you address with your PR',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md54',1,'']]],
  ['additions_10',['Additions',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2changelog.html#autotoc_md46',1,'']]],
  ['address_11',['address',['../structIRData.html#a643d30df67a67c5915fde941c934f9f8',1,'IRData']]],
  ['address_20with_20your_20pr_12',['Cover &lt;strong&gt;all&lt;/strong&gt; occurences of the problem / addition you address with your PR',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md54',1,'']]],
  ['after_20analogwrite_20or_20tone_20or_20after_20running_20a_20motor_13',['Receiving stops after analogWrite() or tone() or after running a motor.',['../index.html#autotoc_md117',1,'']]],
  ['after_20running_20a_20motor_14',['Receiving stops after analogWrite() or tone() or after running a motor.',['../index.html#autotoc_md117',1,'']]],
  ['air_20conditioner_20special_20code_15',['Air conditioner special code',['../group__Airconditoners.html',1,'']]],
  ['aircondition_5flg_16',['Aircondition_LG',['../classAircondition__LG.html',1,'']]],
  ['all_20fields_3a_17',['Print all fields:',['../index.html#autotoc_md87',1,'']]],
  ['all_20strong_20occurences_20of_20the_20problem_20addition_20you_20address_20with_20your_20pr_18',['Cover &lt;strong&gt;all&lt;/strong&gt; occurences of the problem / addition you address with your PR',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md54',1,'']]],
  ['allprotocolsonlcd_19',['ReceiveDemo + AllProtocolsOnLCD',['../index.html#autotoc_md130',1,'']]],
  ['ambiguous_20protocols_20',['Ambiguous protocols',['../index.html#autotoc_md90',1,'']]],
  ['an_20ir_20code_21',['3 ways to specify an IR code',['../index.html#autotoc_md78',1,'']]],
  ['analogwrite_22',['Incompatibilities to other libraries and Arduino commands like tone() and analogWrite()',['../index.html#autotoc_md154',1,'']]],
  ['analogwrite_20or_20tone_20or_20after_20running_20a_20motor_23',['Receiving stops after analogWrite() or tone() or after running a motor.',['../index.html#autotoc_md117',1,'']]],
  ['and_20analogwrite_24',['Incompatibilities to other libraries and Arduino commands like tone() and analogWrite()',['../index.html#autotoc_md154',1,'']]],
  ['and_20arduino_20commands_20like_20tone_20and_20analogwrite_25',['Incompatibilities to other libraries and Arduino commands like tone() and analogWrite()',['../index.html#autotoc_md154',1,'']]],
  ['and_20discussions_26',['Issues and discussions',['../index.html#autotoc_md146',1,'']]],
  ['and_20encoders_20for_20different_20protocols_27',['Decoders and encoders for different protocols',['../group__Decoder.html',1,'']]],
  ['and_20fast_20protocol_28',['and FAST protocol',['../group__TinyReceiver.html',1,'Minimal receiver for NEC and FAST protocol'],['../group__TinySender.html',1,'Minimal sender for NEC and FAST protocol']]],
  ['and_20heatpumpir_29',['rawirdecode and HeatpumpIR',['../index.html#autotoc_md100',1,'']]],
  ['and_20hints_30',['FAQ and hints',['../index.html#autotoc_md116',1,'']]],
  ['and_20pin_20usage_31',['Timer and pin usage',['../index.html#autotoc_md152',1,'']]],
  ['and_20sender_32',['and sender',['../index.html#autotoc_md121',1,'Multiple IR receiver and sender'],['../index.html#autotoc_md109',1,'Tiny NEC receiver and sender']]],
  ['and_20start_20timer_33',['Stop and start timer',['../index.html#autotoc_md157',1,'']]],
  ['and_20tinyreceiver_34',['Use NEC protocol and TinyReceiver',['../index.html#autotoc_md155',1,'']]],
  ['another_20library_35',['Does not work/compile with another library',['../index.html#autotoc_md120',1,'']]],
  ['antena_36',['Antena',['../structAntena.html',1,'']]],
  ['api_20documentation_37',['Creating API documentation',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md57',1,'']]],
  ['arduino_20commands_20like_20tone_20and_20analogwrite_38',['Incompatibilities to other libraries and Arduino commands like tone() and analogWrite()',['../index.html#autotoc_md154',1,'']]],
  ['arduino_20ide_39',['Changing include (&lt;em&gt;.h) files with Arduino IDE',['../index.html#autotoc_md148',1,'']]],
  ['arduino_20ir_20receiving_20libraries_40',['Quick comparison of 5 Arduino IR receiving libraries',['../index.html#autotoc_md162',1,'']]],
  ['arduino_20irremote_41',['Arduino IRremote',['../index.html#autotoc_md59',1,'']]],
  ['arduino_20irremote_20arduino_20irremote_20blob_20master_20changelog_20md_20history_20a_42',['&lt;a href=&quot;https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/changelog.md&quot; &gt;History&lt;/a&gt;',['../index.html#autotoc_md163',1,'']]],
  ['arduino_20irremote_20arduino_20irremote_20blob_20master_20contributors_20md_20contributors_20a_43',['&lt;a href=&quot;https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/Contributors.md&quot; &gt;Contributors&lt;/a&gt;',['../index.html#autotoc_md165',1,'']]],
  ['arduino_20irremote_20blob_20master_20changelog_20md_20history_20a_44',['&lt;a href=&quot;https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/changelog.md&quot; &gt;History&lt;/a&gt;',['../index.html#autotoc_md163',1,'']]],
  ['arduino_20irremote_20blob_20master_20contributors_20md_20contributors_20a_45',['&lt;a href=&quot;https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/Contributors.md&quot; &gt;Contributors&lt;/a&gt;',['../index.html#autotoc_md165',1,'']]],
  ['arduino_20irremote_20releases_20tag_20beta_20release_20a_46',['2.0.1 - 2015/07/26 - &lt;a href=&quot;https://github.com/shirriff/Arduino-IRremote/releases/tag/BETA&quot; &gt;Release&lt;/a&gt;',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2changelog.html#autotoc_md44',1,'']]],
  ['available_47',['available',['../group__Receiving.html#ga4a47f12debf6d5d7273c3e5fb360417a',1,'IRrecv']]]
];
