var searchData=
[
  ['table_20of_20content_0',['Table of content',['../index.html#autotoc_md61',1,'']]],
  ['tag_20beta_20release_20a_1',['2.0.1 - 2015/07/26 - &lt;a href=&quot;https://github.com/shirriff/Arduino-IRremote/releases/tag/BETA&quot; &gt;Release&lt;/a&gt;',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2changelog.html#autotoc_md44',1,'']]],
  ['the_204_20x_20version_2',['the 4 x version',['../index.html#autotoc_md67',1,'Converting your 2.x program to the 4.x version'],['../index.html#autotoc_md65',1,'Converting your 3.x program to the 4.x version']]],
  ['the_204_20x_20versions_20for_20old_20tutorials_3',['Errors with using the 4.x versions for old tutorials',['../index.html#autotoc_md73',1,'']]],
  ['the_20different_20cpu_20boards_4',['Usage of timers for the different CPU / boards',['../group__Timer.html',1,'']]],
  ['the_20fast_20protocol_5',['The FAST protocol',['../index.html#autotoc_md112',1,'']]],
  ['the_20formatting_20style_6',['Use the formatting style',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md53',1,'']]],
  ['the_20new_20hpp_20files_7',['Using the new *.hpp files',['../index.html#autotoc_md77',1,'']]],
  ['the_20problem_20addition_20you_20address_20with_20your_20pr_8',['Cover &lt;strong&gt;all&lt;/strong&gt; occurences of the problem / addition you address with your PR',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md54',1,'']]],
  ['the_20raw_20timing_20data_20received_3a_9',['Print the raw timing data received:',['../index.html#autotoc_md88',1,'']]],
  ['the_20received_20data_3a_10',['Print how to send the received data:',['../index.html#autotoc_md89',1,'']]],
  ['the_20strong_20raw_20data_20strong_20use_3a_11',['To access the &lt;strong&gt;RAW data&lt;/strong&gt;, use:',['../index.html#autotoc_md86',1,'']]],
  ['this_20library_12',['this library',['../index.html#autotoc_md147',1,'Compile options / macros for this library'],['../index.html#autotoc_md125',1,'Examples for this library']]],
  ['this_20program_20useful_20please_20give_20it_20a_20star_13',['If you find this program useful, please give it a star.',['../index.html#autotoc_md60',1,'']]],
  ['tickcounterforisr_14',['TickCounterForISR',['../structirparams__struct.html#aa4a9954a9151a1f61f6f072df6f07618',1,'irparams_struct']]],
  ['timer_15',['timer',['../index.html#autotoc_md156',1,'Change timer'],['../index.html#autotoc_md157',1,'Stop and start timer']]],
  ['timer_20and_20pin_20usage_16',['Timer and pin usage',['../index.html#autotoc_md152',1,'']]],
  ['timer_20required_20for_20sending_17',['No timer required for sending',['../index.html#autotoc_md153',1,'']]],
  ['timers_20for_20the_20different_20cpu_20boards_18',['Usage of timers for the different CPU / boards',['../group__Timer.html',1,'']]],
  ['timing_19',['1. Timing',['../index.html#autotoc_md79',1,'']]],
  ['timing_20data_20received_3a_20',['Print the raw timing data received:',['../index.html#autotoc_md88',1,'']]],
  ['tiny_20nec_20receiver_20and_20sender_21',['Tiny NEC receiver and sender',['../index.html#autotoc_md109',1,'']]],
  ['tinyirreceiver_20usage_22',['TinyIRReceiver usage',['../index.html#autotoc_md110',1,'']]],
  ['tinyirreceivercallbackdatastruct_23',['TinyIRReceiverCallbackDataStruct',['../structTinyIRReceiverCallbackDataStruct.html',1,'']]],
  ['tinyirreceiverstruct_24',['TinyIRReceiverStruct',['../structTinyIRReceiverStruct.html',1,'']]],
  ['tinyirsender_25',['Sending FAST protocol with TinyIRSender',['../index.html#autotoc_md115',1,'']]],
  ['tinyirsender_20usage_26',['TinyIRSender usage',['../index.html#autotoc_md111',1,'']]],
  ['tinyreceiver_27',['Use NEC protocol and TinyReceiver',['../index.html#autotoc_md155',1,'']]],
  ['tinyreceiver_20tinysender_28',['TinyReceiver + TinySender',['../index.html#autotoc_md128',1,'']]],
  ['tinysender_29',['TinyReceiver + TinySender',['../index.html#autotoc_md128',1,'']]],
  ['titles_30',['Use reasonable titles',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md52',1,'']]],
  ['to_20access_20the_20strong_20raw_20data_20strong_20use_3a_31',['To access the &lt;strong&gt;RAW data&lt;/strong&gt;, use:',['../index.html#autotoc_md86',1,'']]],
  ['to_20convert_20old_20msb_20first_2032_20bit_20ir_20data_20codes_20to_20new_20lsb_20first_2032_20bit_20ir_20data_20codes_32',['How to convert old MSB first 32 bit IR data codes to new LSB first 32 bit IR data codes',['../index.html#autotoc_md71',1,'']]],
  ['to_20deal_20with_20protocols_20not_20supported_20by_20irremote_33',['How to deal with protocols not supported by IRremote',['../index.html#autotoc_md103',1,'']]],
  ['to_20new_20lsb_20first_2032_20bit_20ir_20data_20codes_34',['How to convert old MSB first 32 bit IR data codes to new LSB first 32 bit IR data codes',['../index.html#autotoc_md71',1,'']]],
  ['to_20other_20libraries_20and_20arduino_20commands_20like_20tone_20and_20analogwrite_35',['Incompatibilities to other libraries and Arduino commands like tone() and analogWrite()',['../index.html#autotoc_md154',1,'']]],
  ['to_20send_20the_20received_20data_3a_36',['Print how to send the received data:',['../index.html#autotoc_md89',1,'']]],
  ['to_20specify_20an_20ir_20code_37',['3 ways to specify an IR code',['../index.html#autotoc_md78',1,'']]],
  ['to_20the_204_20x_20version_38',['to the 4 x version',['../index.html#autotoc_md67',1,'Converting your 2.x program to the 4.x version'],['../index.html#autotoc_md65',1,'Converting your 3.x program to the 4.x version']]],
  ['tone_20and_20analogwrite_39',['Incompatibilities to other libraries and Arduino commands like tone() and analogWrite()',['../index.html#autotoc_md154',1,'']]],
  ['tone_20or_20after_20running_20a_20motor_40',['Receiving stops after analogWrite() or tone() or after running a motor.',['../index.html#autotoc_md117',1,'']]],
  ['tutorials_41',['Errors with using the 4.x versions for old tutorials',['../index.html#autotoc_md73',1,'']]]
];
