var searchData=
[
  ['pin_0',['Send pin',['../index.html#autotoc_md106',1,'']]],
  ['pin_20usage_1',['Timer and pin usage',['../index.html#autotoc_md152',1,'']]],
  ['pinouts_2',['IRReceiver pinouts',['../index.html#autotoc_md82',1,'']]],
  ['platformio_3',['Modifying compile options / macros with PlatformIO',['../index.html#autotoc_md149',1,'']]],
  ['please_20give_20it_20a_20star_4',['If you find this program useful, please give it a star.',['../index.html#autotoc_md60',1,'']]],
  ['pr_5',['Cover &lt;strong&gt;all&lt;/strong&gt; occurences of the problem / addition you address with your PR',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md54',1,'']]],
  ['print_20all_20fields_3a_6',['Print all fields:',['../index.html#autotoc_md87',1,'']]],
  ['print_20how_20to_20send_20the_20received_20data_3a_7',['Print how to send the received data:',['../index.html#autotoc_md89',1,'']]],
  ['print_20the_20raw_20timing_20data_20received_3a_8',['Print the raw timing data received:',['../index.html#autotoc_md88',1,'']]],
  ['printirresultascvariables_9',['printIRResultAsCVariables',['../group__Receiving.html#ga6f39cb682463248c8b62c4cc82bcefcf',1,'IRrecv']]],
  ['printirresultminimal_10',['printIRResultMinimal',['../group__Receiving.html#ga0862120e518dc16b269e40d282d9e0a9',1,'IRrecv']]],
  ['printirresultrawformatted_11',['printIRResultRawFormatted',['../group__Receiving.html#gaa15d4bb54923f5846b595a6247a4a0d5',1,'IRrecv']]],
  ['printirresultshort_12',['printIRResultShort',['../group__Receiving.html#gaa1ad5e6f5f4802c86cc59d0aece35f7c',1,'IRrecv::printIRResultShort()'],['../group__Receiving.html#gac45e8ead5e96868e61c65cd354758d4d',1,'printIRResultShort(Print *aSerial, IRData *aIRDataPtr, bool aPrintGap):&#160;IRProtocol.hpp'],['../group__Receiving.html#gac45e8ead5e96868e61c65cd354758d4d',1,'printIRResultShort(Print *aSerial, IRData *aIRDataPtr, bool aPrintRepeatGap):&#160;IRProtocol.hpp']]],
  ['printirsendusage_13',['printIRSendUsage',['../group__Receiving.html#gaf9709a0ee5e11bc28f8a83b118348540',1,'IRrecv']]],
  ['problem_20addition_20you_20address_20with_20your_20pr_14',['Cover &lt;strong&gt;all&lt;/strong&gt; occurences of the problem / addition you address with your PR',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md54',1,'']]],
  ['problems_20with_20neopixels_20fastled_20etc_15',['Problems with Neopixels, FastLed etc.',['../index.html#autotoc_md119',1,'']]],
  ['program_20to_20the_204_20x_20version_16',['program to the 4 x version',['../index.html#autotoc_md67',1,'Converting your 2.x program to the 4.x version'],['../index.html#autotoc_md65',1,'Converting your 3.x program to the 4.x version']]],
  ['program_20useful_20please_20give_20it_20a_20star_17',['If you find this program useful, please give it a star.',['../index.html#autotoc_md60',1,'']]],
  ['program_3a_18',['program:',['../index.html#autotoc_md70',1,'New 4.x program:'],['../index.html#autotoc_md69',1,'Old 2.x program:']]],
  ['protocol_19',['protocol',['../index.html#autotoc_md124',1,'Bang &amp; Olufsen protocol'],['../group__TinyReceiver.html',1,'Minimal receiver for NEC and FAST protocol'],['../group__TinySender.html',1,'Minimal sender for NEC and FAST protocol'],['../structIRData.html#abe6f6332009b65cb297c4c593424ecef',1,'IRData::protocol'],['../index.html#autotoc_md112',1,'The FAST protocol']]],
  ['protocol_20and_20tinyreceiver_20',['Use NEC protocol and TinyReceiver',['../index.html#autotoc_md155',1,'']]],
  ['protocol_20characteristics_3a_21',['FAST protocol characteristics:',['../index.html#autotoc_md113',1,'']]],
  ['protocol_20pulse_5fdistance_22',['Protocol=PULSE_DISTANCE',['../index.html#autotoc_md101',1,'']]],
  ['protocol_20unknown_23',['Protocol=UNKNOWN',['../index.html#autotoc_md102',1,'']]],
  ['protocol_20with_20irremote_24',['Sending FAST protocol with IRremote',['../index.html#autotoc_md114',1,'']]],
  ['protocol_20with_20tinyirsender_25',['Sending FAST protocol with TinyIRSender',['../index.html#autotoc_md115',1,'']]],
  ['protocols_26',['Protocols',['../index.html#autotoc_md81',1,'3. Protocols'],['../index.html#autotoc_md95',1,'Handling unknown Protocols'],['../index.html#autotoc_md62',1,'Supported IR Protocols']]],
  ['protocols_27',['protocols',['../md_C_1_2Users_2danib_2Documents_2Arduino_2libraries_2IRremote_2Contributing.html#autotoc_md55',1,'Adding new protocols'],['../index.html#autotoc_md90',1,'Ambiguous protocols'],['../group__Decoder.html',1,'Decoders and encoders for different protocols'],['../index.html#autotoc_md94',1,'RAM usage of different protocols'],['../group__Receiving.html',1,'Receiving IR data for multiple protocols'],['../group__Sending.html',1,'Sending IR data for multiple protocols']]],
  ['protocols_20not_20supported_20by_20irremote_28',['How to deal with protocols not supported by IRremote',['../index.html#autotoc_md103',1,'']]],
  ['public_20ir_20code_20databases_29',['List of public IR code databases',['../index.html#autotoc_md107',1,'']]],
  ['pulse_5fcorrection_5fnanos_30',['PULSE_CORRECTION_NANOS',['../IRremote_8hpp.html#ac836377a7a04f6f4044daab71d9660f9',1,'IRremote.hpp']]],
  ['pulse_5fdistance_31',['Protocol=PULSE_DISTANCE',['../index.html#autotoc_md101',1,'']]],
  ['pulsedistancewidthprotocolconstants_32',['PulseDistanceWidthProtocolConstants',['../structPulseDistanceWidthProtocolConstants.html',1,'']]],
  ['pwm_20signal_20generation_20for_20sending_33',['Hardware-PWM signal generation for sending',['../index.html#autotoc_md158',1,'']]]
];
